import { afterAll, beforeAll, describe, expect, it } from "bun:test"
import { authenticate } from "../../src/auth.js"
import { GameClient } from "../../src/client.js"
import type { Action, Observation } from "../../src/protocol.js"
import { startDevServer, withTimeout, type DevServerHandle } from "../helpers/dev-server.js"
import {
  createUniqueMockWalletAddress,
  MockWalletAdapter,
} from "../helpers/mock-wallet.js"

type RequiredActionType =
  | "move"
  | "attack"
  | "pickup"
  | "use_item"
  | "disarm_trap"
  | "inspect"
  | "interact"
  | "use_portal"

type OptionalActionType = "equip"

interface ActionRunResult {
  observations: Observation[]
  actions: Action[]
  exercised: Set<string>
  seenLegalActions: Set<string>
  extracted: boolean
}

describe("Phase 8 integration: dungeon action coverage", () => {
  let server: DevServerHandle

  beforeAll(async () => {
    server = await startDevServer()
  })

  afterAll(() => {
    server.stop()
  })

  it("covers the non-portal dungeon action surface against the dev stack", async () => {
    const wallet = new MockWalletAdapter({
      address: createUniqueMockWalletAddress("actions"),
    })
    const session = await authenticate(server.apiUrl, wallet)
    const client = new GameClient(server.apiUrl, server.wsUrl, session)

    await client.request("/characters/roll", {
      method: "POST",
      body: JSON.stringify({
        class: "rogue",
        name: `Cov${Date.now().toString().slice(-8)}`,
      }),
    })

    const realm = await client.request<{ id: string }>("/realms/generate", {
      method: "POST",
      body: JSON.stringify({ template_id: "test-dungeon" }),
    })

    try {
      const result = await withTimeout(
        runUntilActionCoverage(client, realm.id, [
          "move",
          "attack",
          "pickup",
          "use_item",
          "disarm_trap",
          "inspect",
          "interact",
        ]),
        40_000,
        "Timed out waiting for dungeon action coverage run to finish",
      )

      const requiredActionTypes: RequiredActionType[] = [
        "move",
        "attack",
        "pickup",
        "use_item",
        "disarm_trap",
        "inspect",
        "interact",
      ]

      for (const actionType of requiredActionTypes) {
        expect(
          result.exercised.has(actionType),
          `Expected to exercise action type "${actionType}"`,
        ).toBeTrue()
      }

      const optionalActionTypes: OptionalActionType[] = ["equip"]
      for (const actionType of optionalActionTypes) {
        if (result.seenLegalActions.has(actionType)) {
          expect(
            result.exercised.has(actionType),
            `Expected to execute "${actionType}" once it became legal`,
          ).toBeTrue()
        } else {
          console.warn(
            `[integration/actions] Skipping strict "${actionType}" assertion because no legal "${actionType}" action was generated by this dungeon run.`,
          )
        }
      }

      expect(result.observations.length).toBeGreaterThan(0)
      expect(result.actions.length).toBeGreaterThan(0)
      expect(result.extracted).toBeFalse()
    } finally {
      client.disconnect()
    }
  }, 45_000)

  it("extracts from a deterministic tutorial run (retreat at entrance preferred over portal)", async () => {
    const wallet = new MockWalletAdapter({
      address: createUniqueMockWalletAddress("portal"),
    })
    const session = await authenticate(server.apiUrl, wallet)
    const client = new GameClient(server.apiUrl, server.wsUrl, session)

    await client.request("/characters/roll", {
      method: "POST",
      body: JSON.stringify({
        class: "knight",
        name: `Port${Date.now().toString().slice(-8)}`,
      }),
    })

    const realm = await client.request<{ id: string }>("/realms/generate", {
      method: "POST",
      body: JSON.stringify({ template_id: "test-tutorial" }),
    })

    try {
      const result = await withTimeout(
        runUntilPortalExtraction(client, realm.id),
        15_000,
        "Timed out waiting for tutorial extraction",
      )

      expect(result.extracted).toBeTrue()
      expect(
        result.actions.some((action) => action.type === "retreat" || action.type === "use_portal"),
      ).toBeTrue()
    } finally {
      client.disconnect()
    }
  }, 20_000)
})

async function runUntilActionCoverage(
  client: GameClient,
  realmId: string,
  requiredActionTypes: RequiredActionType[],
): Promise<ActionRunResult> {
  const observations: Observation[] = []
  const actions: Action[] = []
  const exercised = new Set<string>()
  const seenLegalActions = new Set<string>()
  const interactedTargets = new Set<string>()
  const inspectedTargets = new Set<string>()
  const attemptedMoves = new Set<string>()
  const cameFromDirectionByRoom = new Map<string, "up" | "down" | "left" | "right">()
  let previousRoomId: string | null = null
  let lastMoveDirection: "up" | "down" | "left" | "right" | null = null

  return new Promise<ActionRunResult>((resolve, reject) => {
    void client.connect(realmId, {
      onObservation(observation) {
        if (
          previousRoomId
          && previousRoomId !== observation.position.room_id
          && lastMoveDirection
          && !cameFromDirectionByRoom.has(observation.position.room_id)
        ) {
          cameFromDirectionByRoom.set(
            observation.position.room_id,
            reverseDirection(lastMoveDirection),
          )
        }

        observations.push(observation)
        for (const action of observation.legal_actions) {
          seenLegalActions.add(action.type)
        }

        const action = selectCoverageAction(
          observation,
          exercised,
          interactedTargets,
          inspectedTargets,
          attemptedMoves,
          cameFromDirectionByRoom.get(observation.position.room_id) ?? null,
        )

        actions.push(action)
        exercised.add(action.type)
        previousRoomId = observation.position.room_id
        lastMoveDirection = action.type === "move" ? action.direction : null

        if (requiredActionTypes.every((actionType) => exercised.has(actionType))) {
          resolve({
            observations,
            actions,
            exercised,
            seenLegalActions,
            extracted: false,
          })
          client.disconnect()
          return
        }

        client.sendAction(action)
      },
      onExtracted() {
        resolve({
          observations,
          actions,
          exercised,
          seenLegalActions,
          extracted: true,
        })
      },
      onDeath(data) {
        reject(new Error(`Coverage agent died: ${JSON.stringify(data)}`))
      },
      onError(error) {
        reject(error)
      },
      onClose(event) {
        if (!event.intentional) {
          reject(new Error(`Game socket closed unexpectedly: ${event.code} ${event.reason}`))
        }
      },
    }).catch(reject)
  })
}

async function runUntilPortalExtraction(
  client: GameClient,
  realmId: string,
): Promise<ActionRunResult> {
  const observations: Observation[] = []
  const actions: Action[] = []
  const exercised = new Set<string>()
  const seenLegalActions = new Set<string>()
  const interactedTargets = new Set<string>()
  const attemptedMoves = new Set<string>()
  const cameFromDirectionByRoom = new Map<string, "up" | "down" | "left" | "right">()
  let previousRoomId: string | null = null
  let lastMoveDirection: "up" | "down" | "left" | "right" | null = null

  return new Promise<ActionRunResult>((resolve, reject) => {
    void client.connect(realmId, {
      onObservation(observation) {
        if (
          previousRoomId
          && previousRoomId !== observation.position.room_id
          && lastMoveDirection
          && !cameFromDirectionByRoom.has(observation.position.room_id)
        ) {
          cameFromDirectionByRoom.set(
            observation.position.room_id,
            reverseDirection(lastMoveDirection),
          )
        }

        observations.push(observation)
        for (const action of observation.legal_actions) {
          seenLegalActions.add(action.type)
        }

        const action = selectPortalRunAction(
          observation,
          interactedTargets,
          attemptedMoves,
          cameFromDirectionByRoom.get(observation.position.room_id) ?? null,
        )

        actions.push(action)
        exercised.add(action.type)
        previousRoomId = observation.position.room_id
        lastMoveDirection = action.type === "move" ? action.direction : null
        client.sendAction(action)
      },
      onExtracted() {
        resolve({
          observations,
          actions,
          exercised,
          seenLegalActions,
          extracted: true,
        })
      },
      onDeath(data) {
        reject(new Error(`Portal run died before extraction: ${JSON.stringify(data)}`))
      },
      onError(error) {
        reject(error)
      },
      onClose(event) {
        if (!event.intentional) {
          reject(new Error(`Game socket closed unexpectedly: ${event.code} ${event.reason}`))
        }
      },
    }).catch(reject)
  })
}

function selectCoverageAction(
  observation: Observation,
  exercised: Set<string>,
  interactedTargets: Set<string>,
  inspectedTargets: Set<string>,
  attemptedMoves: Set<string>,
  cameFromDirection: "up" | "down" | "left" | "right" | null,
): Action {
  const unseenInteract = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "interact" }> =>
      action.type === "interact" && !interactedTargets.has(action.target_id),
  )
  if (unseenInteract) {
    interactedTargets.add(unseenInteract.target_id)
    return unseenInteract
  }

  const unseenInspect = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "inspect" }> =>
      action.type === "inspect" && !inspectedTargets.has(action.target_id),
  )
  if (unseenInspect) {
    inspectedTargets.add(unseenInspect.target_id)
    return unseenInspect
  }

  const hpRatio = observation.character.hp.max > 0
    ? observation.character.hp.current / observation.character.hp.max
    : 1
  const useItem = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "use_item" }> => action.type === "use_item",
  )
  if (useItem && (!exercised.has("use_item") || hpRatio <= 0.5)) {
    return useItem
  }

  if (!exercised.has("disarm_trap")) {
    const disarmTrap = observation.legal_actions.find(
      (action): action is Extract<Action, { type: "disarm_trap" }> => action.type === "disarm_trap",
    )
    if (disarmTrap) {
      return disarmTrap
    }
  }

  const visibleEnemyIds = new Set(
    observation.visible_entities
      .filter((entity) => entity.type === "enemy")
      .map((entity) => entity.id),
  )

  const preferredAttack = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "attack" }> =>
      action.type === "attack"
      && action.target_id !== "self"
      && visibleEnemyIds.has(action.target_id),
  )
  if (preferredAttack) {
    return preferredAttack
  }

  const attack = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "attack" }> =>
      action.type === "attack" && action.target_id !== "self",
  )
  if (attack) {
    return attack
  }

  const pickup = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "pickup" }> => action.type === "pickup",
  )
  if (pickup) {
    return pickup
  }

  if (!exercised.has("equip")) {
    const equip = observation.legal_actions.find(
      (action): action is Extract<Action, { type: "equip" }> => action.type === "equip",
    )
    if (equip) {
      return equip
    }
  }

  const usePortal = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "use_portal" }> => action.type === "use_portal",
  )
  if (usePortal && hasCompletedCoverage(exercised)) {
    return usePortal
  }

  const move = chooseCoverageMove(observation, attemptedMoves, cameFromDirection)
  if (move) {
    attemptedMoves.add(`${observation.position.room_id}:${move.direction}`)
    return move
  }

  return { type: "wait" }
}

function selectPortalRunAction(
  observation: Observation,
  interactedTargets: Set<string>,
  attemptedMoves: Set<string>,
  cameFromDirection: "up" | "down" | "left" | "right" | null,
): Action {
  const retreat = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "retreat" }> => action.type === "retreat",
  )
  if (retreat) {
    return retreat
  }
  const usePortal = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "use_portal" }> => action.type === "use_portal",
  )
  if (usePortal) {
    return usePortal
  }

  const unseenInteract = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "interact" }> =>
      action.type === "interact" && !interactedTargets.has(action.target_id),
  )
  if (unseenInteract) {
    interactedTargets.add(unseenInteract.target_id)
    return unseenInteract
  }

  const hpRatio = observation.character.hp.max > 0
    ? observation.character.hp.current / observation.character.hp.max
    : 1
  const heal = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "use_item" }> => action.type === "use_item",
  )
  if (heal && hpRatio <= 0.5) {
    return heal
  }

  const visibleEnemyIds = new Set(
    observation.visible_entities
      .filter((entity) => entity.type === "enemy")
      .map((entity) => entity.id),
  )
  const attack = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "attack" }> =>
      action.type === "attack"
      && action.target_id !== "self"
      && (visibleEnemyIds.size === 0 || visibleEnemyIds.has(action.target_id)),
  )
  if (attack) {
    return attack
  }

  const pickup = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "pickup" }> => action.type === "pickup",
  )
  if (pickup) {
    return pickup
  }

  const equip = observation.legal_actions.find(
    (action): action is Extract<Action, { type: "equip" }> => action.type === "equip",
  )
  if (equip) {
    return equip
  }

  return chooseCoverageMove(observation, attemptedMoves, cameFromDirection) ?? { type: "wait" }
}

function hasCompletedCoverage(exercised: Set<string>): boolean {
  const requiredBeforePortal: Array<Exclude<RequiredActionType, "use_portal">> = [
    "move",
    "attack",
    "pickup",
    "use_item",
    "disarm_trap",
    "inspect",
    "interact",
  ]

  return requiredBeforePortal.every((actionType) => exercised.has(actionType))
}

function chooseCoverageMove(
  observation: Observation,
  attemptedMoves: Set<string>,
  cameFromDirection: "up" | "down" | "left" | "right" | null,
): Extract<Action, { type: "move" }> | undefined {
  const moveActions = observation.legal_actions.filter(
    (action): action is Extract<Action, { type: "move" }> => action.type === "move",
  )
  if (moveActions.length === 0) {
    return undefined
  }

  const target =
    selectVisibleTarget(observation, attemptedMoves)
    ?? nearestTraversalTile(observation, cameFromDirection)

  const current = observation.position.tile
  const tileByCoordinate = new Map(
    observation.visible_tiles.map((tile) => [`${tile.x},${tile.y}`, tile] as const),
  )
  const preferredDirectionOrder: Array<"right" | "down" | "left" | "up"> = [
    "right",
    "down",
    "left",
    "up",
  ]

  const improvingMove = target
    ? moveActions.find((action) => {
    const next = nextPosition(current, action.direction)
    const nextTile = tileByCoordinate.get(`${next.x},${next.y}`)
    if (!nextTile || nextTile.type === "wall") {
      return false
    }

    return manhattanDistance(next, target) < manhattanDistance(current, target)
      })
    : undefined
  if (improvingMove) {
    return improvingMove
  }

  const passableMoves = preferredDirectionOrder
    .map((direction) => moveActions.find((action) => action.direction === direction))
    .filter((action): action is Extract<Action, { type: "move" }> => action !== undefined)
    .filter((action) => {
      const next = nextPosition(current, action.direction)
      const nextTile = tileByCoordinate.get(`${next.x},${next.y}`)
      return nextTile !== undefined && nextTile.type !== "wall"
    })

  return passableMoves.find(
    (action) =>
      action.direction !== cameFromDirection
      && !attemptedMoves.has(`${observation.position.room_id}:${action.direction}`),
  ) ?? passableMoves[0] ?? moveActions[0]
}

function selectVisibleTarget(
  observation: Observation,
  attemptedMoves: Set<string>,
): { x: number; y: number } | null {
  const roomMovePrefix = `${observation.position.room_id}:`
  const exhaustedMoves = ["up", "down", "left", "right"].every((direction) =>
    attemptedMoves.has(`${roomMovePrefix}${direction}`),
  )
  const visibleEntities = observation.visible_entities

  const trappedItem = visibleEntities.find(
    (entity) => entity.type === "item" && entity.position && !exhaustedMoves,
  )
  if (trappedItem?.position) {
    return trappedItem.position
  }

  const enemy = visibleEntities.find((entity) => entity.type === "enemy")
  if (enemy?.position) {
    return enemy.position
  }

  const item = visibleEntities.find((entity) => entity.type === "item")
  if (item?.position) {
    return item.position
  }

  const interactable = visibleEntities.find((entity) => entity.type === "interactable")
  if (interactable?.position) {
    return interactable.position
  }

  return null
}

function nearestTraversalTile(
  observation: Observation,
  cameFromDirection: "up" | "down" | "left" | "right" | null,
): { x: number; y: number } | null {
  const traversalTiles = observation.visible_tiles.filter((tile) =>
    tile.type === "door" || tile.type === "stairs" || tile.type === "stairs_up",
  )
  if (traversalTiles.length === 0) {
    return null
  }

  const current = observation.position.tile
  const preferredTiles = traversalTiles.filter((tile) =>
    !isTileInDirection(current, tile, cameFromDirection),
  )
  if (preferredTiles.length === 0 && cameFromDirection) {
    return null
  }

  return [...(preferredTiles.length > 0 ? preferredTiles : traversalTiles)].sort((left, right) =>
    manhattanDistance(current, left) - manhattanDistance(current, right),
  )[0] ?? null
}

function nextPosition(
  position: { x: number; y: number },
  direction: "up" | "down" | "left" | "right",
): { x: number; y: number } {
  switch (direction) {
    case "up":
      return { x: position.x, y: position.y - 1 }
    case "down":
      return { x: position.x, y: position.y + 1 }
    case "left":
      return { x: position.x - 1, y: position.y }
    case "right":
      return { x: position.x + 1, y: position.y }
  }
}

function manhattanDistance(
  left: { x: number; y: number },
  right: { x: number; y: number },
): number {
  return Math.abs(left.x - right.x) + Math.abs(left.y - right.y)
}

function reverseDirection(direction: "up" | "down" | "left" | "right") {
  switch (direction) {
    case "up":
      return "down"
    case "down":
      return "up"
    case "left":
      return "right"
    case "right":
      return "left"
  }
}

function isTileInDirection(
  current: { x: number; y: number },
  tile: { x: number; y: number },
  direction: "up" | "down" | "left" | "right" | null,
): boolean {
  switch (direction) {
    case "up":
      return tile.y < current.y
    case "down":
      return tile.y > current.y
    case "left":
      return tile.x < current.x
    case "right":
      return tile.x > current.x
    case null:
      return false
  }
}
